config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  root 'visitors#new'

  resources :visitors

  resources :portals do
    resources :versions, shallow: true
    resources :portal_issues, shallow: true
  end

  # resources :portal_issues

  resources :versions do
    resources :issues, shallow: true
  end

  get 'signup' => 'users#new'
  get 'users' => 'users#index'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :password_resets


  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get "login" => 'sessions#new'
  # Deprecating API
  # namespace :api do
  #   namespace :v1 do
  #     get 'visitors/index'
  #     get 'visitors/show'
  #   end
  # end
  # namespace :api do
  #   namespace :v1 do
  #     resources :visitors, only: %i[index show create update destroy]
  #   end
  # end

end

app/models/visitor.rb
class Visitor < ApplicationRecord
  default_scope -> { order("created_at ASC") }
  validates :email, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i # Regex Source: https://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_format_of

  def self.add_attributes(user_agent)
    browser = Browser.new(user_agent)
    { browser: browser.name.to_s.titleize,
      version: browser.full_version.to_s,
      os: "#{browser.platform} #{browser.platform.version}".titleize,
      comp_mode: browser.compatibility_view? }
  end
end

app/controllers/api/v1/visitors_controller.rb
class Api::V1::VisitorsController < ApplicationController
  # def index
  #   render json: Visitor.all
  # end
  #
  # def show
  #   render json: Visitor.find(params[:id])
  # end
  #
  # def create
  #   render json: Visitor.create(visitor_params)
  # end
  #
  # def update
  #   render json: Visitor.update(params[:id], visitor_params)
  # end
  #
  # def destroy
  #   render json: Visitor.destroy(params[:id])
  # end
  #
  # private
  #
  # def visitor_params
  #   params.require(:visitor).permit(:id, :adblock, :email)
  # end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
  before_action :require_employee_user, only: %i[index edit update]

  def index
    @visitors = Visitor.all
    @page_title = 'All Visitors'
  end

  def new
    @visitor = Visitor.new
    @page_title = 'New Visitor'
  end

  def show
    @visitor = Visitor.find(params[:id])
    @page_title = 'Visitor Details'
  end

  def edit
    @visitor = Visitor.find(params[:id])
    @page_title = 'Edit Visitor'
  end

  def create
    browser_attributes = Visitor.add_attributes(request.user_agent)

    params[:visitor]&.merge!(browser_attributes)

    @visitor = Visitor.new(visitor_params)

    if @visitor.save
      VisitorMailer.with(visitor: @visitor).share_information_email.deliver_now
      redirect_to @visitor
    else
      render 'new'
    end
  end

  def update
    @visitor = Visitor.find(params[:id])

    if @visitor.update(visitor_params)
      redirect_to @visitor
    else
      render 'edit'
    end
  end

  def destroy
    @visitor = Visitor&.find(params[:id])
    @user = User&.find_by_id(session[:user_id])
    visitor_email = @visitor.email

    if employee_user || @user&.email == visitor_email
      @visitor.destroy

      if request.referer =~ /users/
        redirect_to request.referer
      elsif employee_user
        redirect_to visitors_path
      elsif visitor_email == @user.email
        redirect_to user_url(@user)
      end
    else
      redirect_to root_url
    end
  end

  def login
    redirect_to login_path
  end

  private

  def visitor_params
    params.require(:visitor).permit(:email, :browser, :version, :os, :comp_mode, :adblock, :css, :notes)
  end
end

app/helpers/visitors_helper.rb
# frozen_string_literal: true

module VisitorsHelper
  @current_version = 0
  @issues = {}
  @portal_issues = {}

  def browser_issue_check(browser, version)
    browser_name = browser.to_s.strip
    version_number = version.to_i

    find_browser_information(browser_name, version_number)
  end

  def find_browser_information(browser, version_int)
    portals = Portal.all
    portal_id = ''

    portals.each do |portal|
      portal_id = portal.id if portal.name == browser
    end

    if portal_id.blank?
      temp_portal = Portal.new(name: browser, current: 0)
      temp_portal.save

      portals = Portal.all

      portals.each do |portal|
        portal_id = portal.id if portal.name == browser
      end
    end

    portal = Portal.find(portal_id)
    @current_version = portal&.current

    @portal_issues = {}
    portal&.portal_issues&.each do |value|
      @portal_issues[value.id] = { name: value.name, description: value.description }
    end

    version_id = ''

    portal&.versions&.each do |temp_version|
      version_id = temp_version.id if temp_version.number == version_int
    end

    @issues = {}

    if version_id.blank?
      temp_version = portal.versions.new(number: version_int)
      temp_version.save
      @issues
    else
      version = portal.versions.find(version_id)

      version&.issues&.each do |issue|
        @issues[issue.id] = { name: issue.name, description: issue.description }
      end
    end
  end

  def outdated(user_version)
    outdated = false
    unless @current_version.zero?
      acceptable = @current_version - 2
      outdated = true if user_version.to_i < acceptable
    end
    outdated
  end
end

app/views/visitors/_form.html.erb
<%=  form_with model: @visitor, local: true do |form| %>
  <% if @visitor.errors.any? %>
      <div id="error_explanation">
        <h5>
            <%= pluralize(@visitor.errors.count, "error") %> prohibited
          this visitor from being saved:
        </h5>
        <ul>
          <% @visitor.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

    <p>
      <strong>Visitor ID:</strong>
      <%= @visitor.id.to_s %><br>

      <strong>Email Address:</strong>
      <%= form.text_field :email%><br>

      <strong>Browser:</strong>
      <%= form.text_field :browser %><br>

      <strong>Version:</strong>
      <%= form.text_field :version %><br>

      <strong>Compatibility View Enabled:</strong>
      <%= form.check_box :comp_mode %><br>

      <strong>AdBlock Enabled:</strong>
      <%= form.check_box :adblock %><br>

      <strong>Operating System:</strong>
      <%= form.text_field :os %><br>

      <% if current_user&.employee? %>
        <strong>Visitor Notes: </strong>
        <%= form.text_area :notes %>
      <% end %>
    </p>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/visitors/edit.html.erb
<h1>Edit Visitor</h1>

<%= render 'form' %>

<%= link_to 'Cancel Edit / Back to Index', visitors_path %>

app/views/visitors/index.html.erb
<h1>All Visitors</h1>
<table>
  <tr>
    <th>Created at</th>
    <th>Email Address</th>
    <th>Browser</th>
    <th>Version</th>
    <th>Compatibility View</th>
    <th>Adblock</th>
    <th>OS</th>
    <th>User ID</th>
    <th>Notes</th>
  </tr>

  <% @visitors.each do |visitor| %>
    <tr>
      <td><%= visitor.created_at %></td>
      <td><%= visitor.email %></td>
      <td><%= visitor.browser %></td>
      <td><%= visitor.version %></td>
      <td><%= visitor.comp_mode %></td>
      <td><%= visitor.adblock%></td>
      <td><%= visitor.os.to_s %></td>
      <td><%= visitor.id %></td>
      <td><%= visitor.notes %></td>
      <td><%= link_to 'Show', visitor_path(visitor) %></td>
      <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
      <td><%= link_to 'Delete', visitor_path(visitor),
                      method: :delete,
                      data:   { confirm: 'Are you certain?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Visitor', new_visitor_path %><br>
<%= link_to 'Browser Management Page', portals_path %>

app/views/visitors/new.html.erb
<h1>Create New Visitor Record</h1>

<%= form_with model: @visitor, local: true do |form| %>

  <% if @visitor.errors.any? %>
    <div class="error_explanation">
      <h5>
        <%= pluralize(@visitor.errors.count, "error") %> prohibited
        your browser information from being saved:
      </h5>
      <ul>
        <% @visitor.errors.full_messages.each do |msg| %>
          <li class="error"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :email %>
  <%= form.text_field :email, placeholder: 'youremail@example.com' %> <br>
  <%= form.hidden_field :adblock, value: false %>
  <%= form.hidden_field :css %>

  <p>
    <i>
      By clicking <strong>Submit Information</strong>, I agree to allow this program collect information regarding my browser and computer.
    </i>
  </p>
  <%= form.submit "Submit Information" %>
<% end %>

<% if !current_user.nil? %>
  <i>
    If you would like to delete previously submitted records,
    please <%= link_to 'visit your profile page', user_url(current_user) %>.<br>
    This will also allow you to access all previous visits recorded with your email address: <%= current_user.email %>.
  </i>
<% else %>
  <i>
    If you would like to delete previously submitted records, please <%= link_to 'login', login_url %>
    or <%= link_to 'create an account', signup_url %>.<br>
    This will also allow you to access all previous visits recorded with your email address.
  </i>
<% end %>

<!--  Adblock JS solution found in [this Stack Overflow answer](https://stackoverflow.com/a/34745228).-->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" onerror="adBlockFunction();"></script>
<script> function adBlockFunction() {
  document.getElementById('visitor_adblock').value = true;
  console.log("Detected Adblocker.");
  }

// Unable to check CSS on another website. Can't do unless incorporated in the main site:
// Failed to load https://app.kapost.com/users/sign_in: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
// fetch("https://napa-prod-kapost.netdna-ssl.com/assets/login-d84ed8e7240695928708bf27ebc9b43586c2fec089c3c1b6c506133d8ea6a414.css")
//   .then(function(data) {
//     // Here you get the data to modify as you please
//
//     })
//   .catch(function(error) {
//     // If there is any error you will catch them here
//     console.log("Failed to load CSS.")
//   });
</script>

app/views/visitors/show.html.erb
<p>

  <% if current_user&.employee? %>
    <strong>Visitor ID:</strong>
    <%= @visitor.id.to_s %><br>

    <strong>Email Address:</strong>
    <%= @visitor.email %><br>
  <% elsif current_user %>
    <strong>Email Address:</strong>
    <%= @visitor.email %><br>
  <% end %>

  <strong>Browser:</strong>
  <%= @visitor.browser %>
  <%= @visitor.version %> <br>

  <% browser_issue_check(@visitor.browser, @visitor.version) %>

   <% if @visitor.browser == "Internet Explorer" %>
    <strong>Compatibility View Enabled:</strong>
    <%= @visitor.comp_mode %> <br>
    <% if @visitor.comp_mode %>
        Internet Explorer's Compatibility mode has been detected. This feature forces <%= ENV['COMPANY_WEBSITE_NAME'] %> to load as if you were using a much older version of IE. Please disable this setting for viewing <%= ENV['COMPANY_WEBSITE_NAME'] %>. For mor information on disabling compatibility mode, please visit <%= link_to 'this external article', "https://www.howtogeek.com/128289/how-to-disable-compatibility-mode-in-internet-explorer/" %>.
      <br>
    <% end %>
  <% end %>

  <% if @visitor.browser =="Microsoft Edge" %>
    Microsoft Edge is not currently a support browser for this application. For more information please visit our
    <%= link_to 'browser support help article', "https://help.kapost.com/hc/en-us/articles/212465607-Browser-Support" %>.
    <br>
  <% end %>

  <% if outdated(@visitor.version) %>
    <strong>Version Outdated:</strong>
    Your browser is out of date and needs to be updated. <%= ENV['COMPANY_WEBSITE_NAME'] %> is tested to ensure that it works with the last two major releases of major browsers. Your browser is currently <% @current_version - @visitor.version.to_i %> versions behind the current version.
    <br>
  <% end %>

  <strong>AdBlock Enabled:</strong>
  <% if @visitor.adblock %>
    <strong>True</strong> <br>
    Please consider adding <%= ENV['COMPANY_WEBSITE_NAME'] %> to your AdBlocker's exception list. AdBlockers have been know to cause issues for some users with various parts of our application, like uploading files or editing some fields.
  <% else %>
    False
  <% end %>
  <br>

  <strong>Operating System:</strong>
  <%= @visitor.os.titleize%>

  <% if current_user&.employee? %>
    <br><strong>Visitor Notes:</strong> <%= @visitor.notes %><br>
  <% end %>

  <br>
  <strong>Known browser wide issues with <%= @visitor.browser %>:</strong><br>
  <% if @portal_issues.nil? %>
    No known issues. <br>
  <% elsif @portal_issues.empty? %>
    No known issues. <br>
  <% else %>
    <table>
      <tr>
        <% @portal_issues&.each do |_x, issue| %>
          <td>
            <i><%= issue[:name] %></i><br>
            <%= issue[:description] %>
          </td>
        <% end %>
      </tr>
    </table>
    <br>
  <% end %>

  <strong>Known issues with <%= "#{@visitor.browser} #{@visitor.version}" %>:</strong><br>
  <% if @issues.nil? %>
    No known issues. <br>
  <% elsif @issues.empty? %>
    No known issues. <br>
  <% else %>
    <table>
      <tr>
        <% @issues&.each do |_x, issue| %>
          <td>
            <i><%= issue[:name] %></i><br>
            <%= issue[:description] %>
          </td>
        <% end %>
      </tr>
    </table>
    <br>
  <% end %>
</p>

<br>
<% if current_user&.employee? %>
  <%= link_to 'Edit Visitor', edit_visitor_path(@visitor) %> |
  <%= link_to 'Back to Index', visitors_path %>
<% end %>

<% if !current_user.nil? %>
  <p>
    <i>If you would like to delete this record, please <%= link_to 'visit your profile page', user_url(current_user) %>.<br>
      This will also allow you to access all previous visits recorded with your email address: <%= @visitor.email %>.</i>
  </p>
<% else %>
    <p>
      <i>If you would like to delete this record, please <%= link_to 'login', login_url %> or <%= link_to 'create an account', signup_url %>.<br>
        This will also allow you to access all previous visits recorded with your email address.</i>
    </p>
<%  end %>