config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  root 'visitors#new'

  resources :visitors

  resources :portals do
    resources :versions, shallow: true
    resources :portal_issues, shallow: true
  end

  # resources :portal_issues

  resources :versions do
    resources :issues, shallow: true
  end

  get 'signup' => 'users#new'
  get 'users' => 'users#index'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :password_resets


  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get "login" => 'sessions#new'
  # Deprecating API
  # namespace :api do
  #   namespace :v1 do
  #     get 'visitors/index'
  #     get 'visitors/show'
  #   end
  # end
  # namespace :api do
  #   namespace :v1 do
  #     resources :visitors, only: %i[index show create update destroy]
  #   end
  # end

end

app/models/issue.rb
class Issue < ApplicationRecord
  default_scope -> { order("created_at ASC") }
  belongs_to :version

  validates :name, presence: true
  validates :description, presence: true,
                          length: { minimum: 5 }
end

app/controllers/issues_controller.rb
# frozen_string_literal: true

class IssuesController < ApplicationController
  before_action :require_employee_user, only: %i[index show new create update edit destroy]

  def index
    @version = Version.find(params[:version_id])
    @issue = @version.issues.all
    @page_title = "#{@version.portal.name.titleize} #{@version.number} Issues"
  end

  def new
    @version = Version.find(params[:version_id])
    @issue = @version.issues.new
    @page_title = 'New Issue'
  end

  def edit
    @issue = Issue.find(params[:id])
    @page_title = "Edit Issue #{@issue.name.titleize}"
  end

  def create
    @version = Version.find(params[:version_id])
    @issue = @version.issues.new(issue_params)

    if @issue.save
      redirect_to issue_path(@issue)
    else
      render :new
    end
  end

  def show
    @issue = Issue.find(params[:id])
    @page_title = "Issue #{@issue.name.titleize} Details"
  end

  def update
    @issue = Issue.find(params[:id])

    if @issue.update(issue_params)
      redirect_to @issue
    else
      render 'edit'
    end
  end

  def destroy
    @issue = Issue.find(params[:id])
    saved_version_path = @issue.version_id
    @issue.destroy
    redirect_to version_issues_path(saved_version_path)
  end

  private

  def issue_params
    params.require(:issue).permit(:name, :description)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/edit.html.erb
<h1>Edit Issue <%= @issue.name.strip %></h1>
<%= form_with model: @issue do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h5>
        <%= pluralize(@issue.errors.count, "error") %> prohibited
        the issue from being saved:
      </h5>
      <ul>
        <%= @issue.errors.full_messages.each do |msg| %>
          <li class="error"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Issue Name" %>
    <%= f.text_field :name, required: true %><br>

    <%= f.label :description %>
    <%= f.text_area :description, required: true, minlength: 5 %><br>
  </p>

  <%= f.submit %>
<% end %>

<%= link_to 'Back to Issues', version_issues_path(@issue.version) %>

app/views/issues/index.html.erb
<h1><%= "#{@version.portal.name.strip}(#{@version.number}) Issues" %></h1>
<table>
  <tr>
    <td>Name</td>
    <td>Description</td>
  </tr>

  <% @version.issues.each do |issue| %>
    <tr>
      <td><%= issue.name %></td>
      <td><%= issue.description %></td>
      <td><%= link_to 'Show', issue_path(issue) %></td>
      <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
      <td><%= link_to 'Delete', issue_path(issue),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

</table>
<%= link_to 'Add New Issue', new_version_issue_path(@version) %> |
<%= link_to 'Back to Browser Page', portals_path(@version.portal) %>

app/views/issues/new.html.erb
<h1>Add New Issue for <%= @version.portal.name.strip %> version <%= @version.number %></h1>
<%= form_with(model: @issue, url: version_issues_path) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h5>
        <%= pluralize(@issue.errors.count, "error") %> prohibited
        the issue from being saved:
      </h5>
      <ul>
        <%= @issue.errors.full_messages.each do |msg| %>
          <li class="error"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Issue Name" %>
    <%= f.text_field :name, required: true %><br>

    <%= f.label :description %>
    <%= f.text_area :description, required: true, minlength: 5 %><br>
  </p>

  <%= f.submit %>
<% end %>

<%= link_to 'Back to Issues', version_issues_path(@version) %>

app/views/issues/show.html.erb
<h1><%= @issue.name.titleize%></h1>
<%= link_to 'Edit Issue', edit_issue_path(@issue) %>
<p>
  <i>This issue affects <%= @issue.version.portal.name.strip %> version <%= @issue.version.number %>.</i>
</p>
<p>
  <strong>Description:</strong>
  <%= @issue.description %><br>
</p>

<%= link_to 'Back to Issue Index', version_issues_path(@issue.version) %> |
<%= link_to "Back to version #{@issue.version.number}", version_path(@issue.version) %>