config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  root 'visitors#new'

  resources :visitors

  resources :portals do
    resources :versions, shallow: true
    resources :portal_issues, shallow: true
  end

  # resources :portal_issues

  resources :versions do
    resources :issues, shallow: true
  end

  get 'signup' => 'users#new'
  get 'users' => 'users#index'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :password_resets


  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get "login" => 'sessions#new'
  # Deprecating API
  # namespace :api do
  #   namespace :v1 do
  #     get 'visitors/index'
  #     get 'visitors/show'
  #   end
  # end
  # namespace :api do
  #   namespace :v1 do
  #     resources :visitors, only: %i[index show create update destroy]
  #   end
  # end

end

app/models/portal.rb
class Portal < ApplicationRecord
  default_scope -> { order("created_at ASC") }
  has_many :versions, dependent: :destroy
  has_many :portal_issues, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :current, numericality: { only_integer: true }, presence: true
end

app/controllers/portals_controller.rb
# frozen_string_literal: true

class PortalsController < ApplicationController
  before_action :require_employee_user, only: %i[index show new create update edit destroy]

  def index
    @portals = Portal.all
    @page_title = 'All Browsers'
  end

  def new
    @portal = Portal.new
    @page_title = 'New Browser'
  end

  def show
    @portal = Portal.find(params[:id])
    @page_title = "#{@portal.name} Details"
  end

  def edit
    @portal = Portal.find(params[:id])
    @page_title = "Edit #{@portal.name}"
  end

  def create
    @portal = Portal.new(portal_params)

    if @portal.save
      redirect_to @portal
    else
      render 'new'
    end
  end

  def update
    @portal = Portal.find(params[:id])

    if @portal.update(portal_params)
      redirect_to @portal
    else
      render 'edit'
    end
  end

  def destroy
    @portal = Portal.find(params[:id])
    @portal.destroy

    redirect_to portals_path
  end

  private

  def portal_params
    params.require(:portal).permit(:name, :current)
  end
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/portals/edit.html.erb
<h1>Edit Browser</h1>
  <%=  form_with model: @portal, local: true do |form| %>
    <% if @portal.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@portal.errors.count, "error") %> prohibited
          this visitor from being saved:
        </h2>
        <ul>
          <% @portal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <p>
    <strong>Browser:</strong>
    <%= form.text_field :name %><br>
  </p>
  <p>
    <strong>Current Version:</strong>
    <%= form.number_field :current %>
  </p>

    <%= form.submit "Update Browser" %><br>
  <% end %>
<br>
<%= link_to 'Cancel Edit / Back to Browsers', portals_path %>

app/views/portals/index.html.erb
<h1>All Browsers</h1>
<table>
  <tr>
    <th>Browser</th>
    <th>Current</th>
    <th>Versions</th>
  </tr>

  <% @portals.each do |browser| %>
      <tr>
        <td><%= browser.name %></td>
        <td><%= browser.current %></td>
        <td>
            <% browser.versions.each do |version| %>
              <%= version.number %><%= ", " unless version == browser.versions.last %>
            <% end %>
        </td>
        <td><%= link_to 'Show', portal_path(browser) %></td>
        <td><%= link_to 'Edit', edit_portal_path(browser) %></td>
        <td><%= link_to 'Delete', portal_path(browser),
                        method: :delete,
                        data:   { confirm: 'Are you certain?' } %></td>
      </tr>
    <% end %>
  </table>
<%= link_to 'Create New Browser', new_portal_path %> |
<%= link_to 'Go to Visitors Index', visitors_path %>

<br/>
<br/>
<br/>
<div id="react-div" >test</div>

app/views/portals/new.html.erb
<h1>Create New Browser</h1>

<%= form_with model: @portal, local: true do |f| %>
  <% if @portal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@portal.errors.count, "error") %> prohibited
        the new browser from being saved:
      </h2>
      <ul>
        <%= @portal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :current, "Current Version" %>
  <%= f.number_field :current%> <br>

  <%= f.submit "Create Browser" %>
<% end %>
<br>
<%= link_to 'Browser Management Page', portals_path %>

app/views/portals/show.html.erb
<h1><%= @portal.name %></h1>

<strong>Current Version:</strong><%= @portal.current %><br>
<%= link_to "Edit #{@portal.name}", edit_portal_path(@portal.id) %>

<h2>Browser Wide Issues:</h2>
  <table>
    <tr>
      <th>Name</th>
      <th>Issue</th>
    </tr>

    <% @portal.portal_issues.each do |issue| %>
      <tr>
        <td><%= issue.name %></td>
        <td><%= issue.description %></td>
        <td><%= link_to 'Show', portal_portal_issues_path(issue) %></td>
        <td><%= link_to 'Edit', edit_portal_issue_path(issue) %></td>
        <td><%= link_to 'Delete', portal_portal_issues_path(issue),
                        method: :delete,
                        data:   { confirm: 'Are you certain?' } %></td>
      </tr>
    <% end %>
  </table>

<h2>Versions Specific Issues:</h2>
<%= render 'versions/index'%><br>
<%= link_to 'New Version', new_portal_version_path(@portal)  %> |
<%= link_to 'Version Management Page', portal_versions_path(@portal)  %> |
<%= link_to 'Browser Management Page', portals_path %>