config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  root 'visitors#new'

  resources :visitors

  resources :portals do
    resources :versions, shallow: true
    resources :portal_issues, shallow: true
  end

  # resources :portal_issues

  resources :versions do
    resources :issues, shallow: true
  end

  get 'signup' => 'users#new'
  get 'users' => 'users#index'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :password_resets


  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get "login" => 'sessions#new'
  # Deprecating API
  # namespace :api do
  #   namespace :v1 do
  #     get 'visitors/index'
  #     get 'visitors/show'
  #   end
  # end
  # namespace :api do
  #   namespace :v1 do
  #     resources :visitors, only: %i[index show create update destroy]
  #   end
  # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Browser Detect<%= ": #{@page_title}" unless @page_title.nil? %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar">
      <div class="row">
          <% if employee_user %>
            <%= link_to 'Browsers', portals_path %> |
            <%= link_to 'Registered Users', users_path %> |
            <%= link_to 'Visitors', visitors_path %>
          <% end %>
      <% if current_user %>
        <div class="u-pull-right">
          <%= link_to "#{current_user.email}", user_url(current_user) %> |
          <%= link_to 'Log out', logout_path, method: 'delete' %>
        </div>
      <% else %>
          <%= link_to 'Login', login_path %> |
          <%= link_to 'Create an Account', signup_path %>
      <% end %>
      </div>
    </nav>
    <br>

    <%= render 'shared/flash_messages' unless flash.empty? %>


    <!-- Before Yield -->
      <%= yield %>
    <!-- After Yield -->
  </body>
  <footer>
    <div class="u-pull-right">
      <%= link_to 'View Source on GitHub', 'https://github.com/meagerfindings/browser_detect' %>
      <%= link_to image_tag('GitHub-Mark-120px-plus.png',
                            size: '15',
                            alt: 'View source on GitHub.'),
                  'https://github.com/meagerfindings/browser_detect' %>
    </div>
  </footer>
</html>